### ISSUE TITLE
Initial implementation of g8os hub

### ISSUE THREAD

**Issue by FastGeert** [g8os/hub#1]
- Based on Caddy (already integrated with IYO)
- When tar.gz is uploaded, it is picked up automatically and parsed into ARDB / flist, and published on the /<<< iyo account name >>>/targzfilename.plist
- Uploading a .md file is also possible and will also be placed into the /<<< iyo account name >>>/ directory
- Interface is just the default directory listing served by Caddy

**Comment by despiegk** [comment]
there is a much more fancy filemanager as well, suggest to enable that one too.
