### ISSUE TITLE
Internal Server Error when uploading tar

### ISSUE THREAD

**Issue by yveskerwyn** [g8os/hub#10]
![screen shot 2017-05-04 at 16 47 08](https://cloud.githubusercontent.com/assets/13795109/25709382/76459b64-30e9-11e7-88cb-7262c33af989.png)

**Comment by maxux** [comment]
Can you try again ?

**Comment by yveskerwyn** [comment]
![screen shot 2017-05-04 at 16 51 04](https://cloud.githubusercontent.com/assets/13795109/25709518/e6099b94-30e9-11e7-8a0e-476154db3394.png)

**Comment by yveskerwyn** [comment]
![screen shot 2017-05-04 at 16 51 39](https://cloud.githubusercontent.com/assets/13795109/25709571/fbb1ffd6-30e9-11e7-8ed3-2867ab417897.png)

**Comment by yveskerwyn** [comment]
Works now
